services:
    postgres:
        image: postgres:15-alpine
        container_name: difme-dev-postgres
        environment:
            POSTGRES_DB: difme
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pass
        ports:
            - "5434:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - difme_network
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres}"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
        driver: local

networks:
    difme_network:
        driver: bridge
